### ISSUE TITLE
Update eslint Package

### ISSUE THREAD

**Issue by mendelB** [DoSomething/eslint-config#11]
Way over at [Phoenix](https://github.com/DoSomething/phoenix-next) land, we've run into some rather annoying `jsx-a11y` errors related to https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/440

(https://github.com/DoSomething/phoenix-next/pull/1318#discussion_r266117113, https://git.io/fjejq)

This issue seems to have been [fixed in an updated version](https://github.com/evcohen/eslint-plugin-jsx-a11y/pull/437). All we need to do is update `eslint`!

**Comment by DFurnes** [comment]
This is done!
